version: '3.8'

services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul-server
    restart: always
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    volumes:
      - ./data:/consul/data
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect=1 -ui -client=0.0.0.0 -bind=0.0.0.0 -data-dir=/consul/data"
