services:
  pg-db:
    image: postgres:16-alpine
    container_name: claim-postgres
    environment:
      POSTGRES_DB: test-db
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: postgress
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgress -d test-db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: